### ISSUE TITLE
By the guide , there was no reference to working with xaml based build definitions

### ISSUE THREAD

**Issue by boazlevinson** [ALM-Rangers/Migrate-assets-from-RM-server-to-VSTS#27] opened 2016-08-30 16:43 UTC
Hi,

How does this all work if insead of a tfs 15 build definition , i have a tfs 13 build definition upgraded to tfs 15, which is now so called xaml based . those builds cannot be edited .  what should i do if i want to combine those build definitions with the migrated release scripts ?

makes sense to mention it , right ?

**Comment by wpschaub** [comment] 2016-09-02 16:31
If the issue is "_How do I deal with XAML build process templates that do deployment activities_" then it's out of scope for this project.

If the issue is "_How do I deploy the output of a XAML build with the Release hub_" then there's functionally no difference. Just link the XAML build as an artifact.

Can you please clarify what you mean with "_those builds can't be edited_"?

**Comment by boazlevinson** [comment] 2016-09-03 23:58
Hi ,

I will rephrase the question .
1.Keeping what we have :
I have xaml build definitions , of tfs 2013 , and custom activities inside them . their build template is the one i took from release management 2013 u4 , cause i also have rm 13 release templates .  my goal is to first use the current workflow  while upgrading to TFS 15 , without having to migrate build definitions or rm templates . and slowly to convert them to 15 builds and releases ,so currently , if we upgrade to tfs 15 from 13 , will our tfs 13 builds and rm 13 attached releases be harmed ? 

2.When we will migrate :
what i meant , about the editing was that you have no edit option on tfs 15 web UI to edit the xaml based build definitions , they are treated as a black box , and does not have any capability that the new vnext builds has . it could be great to learn how to incorporate them in a new tfs 15 build . you mentioned using them as an artifact , but remember , in my case they also have a trigger to rm 13 (cause there is an rm tfvc 13 release template attached to them, on top of that , i added a custom activity to this release template . ) how can i make it all work? 
by the way , we have about 4 team collections we want to unify in the future , should we still maintain all our build servers (each has it's own build definitions) for each team collection  as long as we work with the xaml base build definitions ?

more a comment than a question . there isn't a lot of information out there for rm 15 and tfs 15 at all , so searching the web is not a productive act for this . in general , we need more guides and information for how to migrates all we did at 2013 , TFS builds and RM 13 update 4 recipes .

Thanks !

Boaz

**Comment by wpschaub** [comment] 2016-09-06 16:41
Boaz, here's feedback from the team:
1. XAML builds from TFS 13 will continue to work in TFS 15. You will also need to upgrade the server-client version of RM to server-client version of RM 2015 and the corresponding build template to invoke RM. These RM flows will continue working with TFS 15.
2. Unlike old builds, neither the old releases nor the old release templates can be viewed/edited in the web UI. The new web-based RM service is entirely different and the web UI hasn’t been built for the older version at all. You would have to continue to use the WPF client for these operations. If you upgraded to RM 15 as described above, your new builds will be able to trigger releases in the RM 2015 server-client version. 

Please use the [tfsbuild ](https://social.msdn.microsoft.com/Forums/en-US/home?forum=tfsbuild) or [tfservice ](https://social.msdn.microsoft.com/Forums/en-US/home?forum=TFService)  forums if you have further questions.

**Closed as completed** 2016-11-27 02:07 UTC
